Vladimir
TimaArkhipov/Java_Project pull request #20
Opened 2021-11-27 07:07 UTC by Bolamir

2021-11-29 11:08 UTC, TimaArkhipov commented on Deal.java
> +	private int pid;
Мне кажется излишним 2 переменных, которые по сути выполняют одну функцию(pid и countOfDeal), но если ты всё же их делаешь, то переделай нормально под них все функции, где они участвуют.

2021-11-29 11:09 UTC, TimaArkhipov commented on Database.java
> +package com.example.timetracker;
Ты что, Database не залил, а просто изменил в gitHub вставкой кода из Android Studio

2021-11-29 11:11 UTC, TimaArkhipov commented on TaskReport.java
> +	public TaskReport(){
Не нужно оставлять такие большие пропуски, пусть будет как в прошлой версии

2021-11-29 11:12 UTC, TimaArkhipov commented on TaskReport.java
> +						+ "Comment: "+ comment+ '\n';
Когда переделывал забыл добавить "Grade:"

2021-11-29 11:14 UTC, TimaArkhipov commented on activity_secundomer.xml
> +    tools:context=".TimerActivity">
Тут скорее всего SecundomerActivity

2021-11-29 11:18 UTC, TimaArkhipov commented on Deal.java
> +
Много пустоты

2021-11-29 11:19 UTC, TimaArkhipov commented on Deal.java
> +
Почему убрал setId?

2021-11-29 11:20 UTC, TimaArkhipov commented on Database.java
> +package com.example.timetracker;
Комментарии ещё надо подправить для читаемости(если они вообще нужны нам)

2021-11-29 11:39 UTC, Bolamir commented on Deal.java
> +	private int pid;
countOfDeal меняется в зависимости от количества дел и является общим полем для всех дел
pid не меняется и для каждого дела это поле свое

2021-11-29 11:39 UTC, Bolamir commented on Deal.java
> +
Идентификатор не меняется

2021-11-29 11:45 UTC, TimaArkhipov requested changes
Доработать в соответствии с комментариями

2021-12-12 15:20 UTC, Bolamir commented
Исправлено

2021-12-12 15:22 UTC, Bolamir commented
Исправлено

2021-12-12 15:22 UTC, closed without merging